import os
import sys
import cv2
import numpy as np
import time
import argparse
import threading
import subprocess
from collections import deque
from pathlib import Path

sys.path.append(str(Path(__file__).parent))

from ultralytics import YOLO
import tensorflow as tf

from extract_pose import RTMPoseInferencer, restore_coords
from build_sequences import FeatureExtractor

# Colors for the dashboard
COLOR_BG = (15, 15, 15)
COLOR_PANEL = (30, 30, 30)
COLOR_ACCENT = (0, 255, 127)  # Spring Green
COLOR_ALERT = (0, 0, 255)     # Red
COLOR_TEXT = (240, 240, 240)
COLOR_TRACK = (255, 165, 0)   # Orange
COLOR_INFO = (0, 191, 255)    # Deep Sky Blue

# ---------------- STREAM GRABBER ----------------
class FastStreamGrabber:
    def __init__(self, source):
        self.cap = cv2.VideoCapture(source)
        if not self.cap.isOpened():
            self.cap = cv2.VideoCapture(source, cv2.CAP_V4L2)

        if not self.cap.isOpened():
            raise RuntimeError(f"Could not open source: {source}")

        self.native_fps = self.cap.get(cv2.CAP_PROP_FPS) or 12.0
        self.width = int(self.cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        self.height = int(self.cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

        self.lock = threading.Lock()
        self.frame = None
        self.ret = False
        self.stopped = False
        self.frame_idx = 0

        self.ret, frame = self.cap.read()
        if self.ret:
            self.frame = cv2.resize(frame, (1280, 720))
        
        self.thread = threading.Thread(target=self._update, daemon=True)
        self.thread.start()

    def _update(self):
        while not self.stopped:
            ret, frame = self.cap.read()
            if ret:
                frame = cv2.resize(frame, (1280, 720))
            with self.lock:
                self.ret = ret
                if ret:
                    self.frame = frame
                    self.frame_idx += 1
            if not ret:
                time.sleep(0.01)

    def read(self, last_idx=-1):
        with self.lock:
            if self.frame is None or self.frame_idx <= last_idx:
                return self.ret, None, self.frame_idx
            return self.ret, self.frame.copy(), self.frame_idx

    def stop(self):
        self.stopped = True
        if self.thread.is_alive():
            self.thread.join(timeout=1)
        self.cap.release()

# ---------------- RECORDING ----------------
class RecordingManager:
    def __init__(self, fps, width, height, output_dir="data/recordings", pre_buffer_sec=2, cooldown_sec=3):
        self.fps = fps
        self.width = width
        self.height = height
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

        self.frame_buffer = deque(maxlen=int(fps * pre_buffer_sec))
        self.cooldown_len = int(fps * cooldown_sec)

        self.process = None
        self.cooldown = 0
        self.active = False

    def update(self, frame, alert, count=1):
        frame_copy = frame.copy()
        for _ in range(count):
            self.frame_buffer.append(frame_copy)

        started_now = False
        if alert:
            self.cooldown = self.cooldown_len
            if not self.active:
                self.start()
                started_now = True

        if self.active and not started_now:
            try:
                frame_bytes = frame.tobytes()
                for _ in range(count):
                    self.process.stdin.write(frame_bytes)
            except BrokenPipeError:
                print("[REC] FFmpeg pipe broken. Stopping recording.")
                self.stop()
            
            if not alert:
                self.cooldown -= count
                if self.cooldown <= 0:
                    self.stop()

    def start(self):
        ts = time.strftime("%Y%m%d-%H%M%S")
        path = os.path.join(self.output_dir, f"fight_{ts}.mp4")
        
        command = [
            'ffmpeg',
            '-y', # overwrite
            '-f', 'rawvideo',
            '-vcodec', 'rawvideo',
            '-s', f'{self.width}x{self.height}',
            '-pix_fmt', 'bgr24',
            '-r', str(self.fps),
            '-i', '-', # input from pipe
            '-c:v', 'libx264',
            '-pix_fmt', 'yuv420p',
            '-preset', 'veryfast',
            '-crf', '23',
            '-tune', 'zerolatency',
            '-movflags', '+faststart',
            '-metadata', 'title=Violence Detection Alert',
            '-metadata', f'creation_time={time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}',
            '-metadata', 'comment=Generated by Gemini-CLI Fight Detection Pipeline',
            path
        ]

        try:
            self.process = subprocess.Popen(command, stdin=subprocess.PIPE, stderr=subprocess.DEVNULL)
            
            # Write pre-buffer frames
            while self.frame_buffer:
                self.process.stdin.write(self.frame_buffer.popleft().tobytes())

            self.active = True
            print(f"[REC] started (FFmpeg H.264): {path}")
        except Exception as e:
            print(f"[REC] Failed to start FFmpeg: {e}")
            self.active = False

    def stop(self):
        if self.process:
            try:
                self.process.stdin.close()
                self.process.wait(timeout=5)
            except Exception as e:
                print(f"[REC] Error closing FFmpeg: {e}")
                self.process.kill()
        
        self.process = None
        self.active = False
        print("[REC] stopped and finalized")

# ---------------- PIPELINE ----------------
class InferencePipeline:
    def __init__(self, args):
        self.args = args

        print("Loading Models...")
        self.det_model = YOLO(args.det_model)
        self.pose_model = RTMPoseInferencer(args.pose_model, device=args.device, num_threads=args.pose_threads)

        self.interpreter = tf.lite.Interpreter(model_path=args.tcn_model)
        self.interpreter.allocate_tensors()
        self.inp = self.interpreter.get_input_details()
        self.out = self.interpreter.get_output_details()

        self.feature_extractor = FeatureExtractor(sequence_length=36)

        # state
        self.prev_centers = {}
        self.smoothed_bboxes = {}
        self.pose_memory = {}
        self.pair_buffers = {}
        self.last_seen = {}

        # tuning
        self.proximity = args.proximity
        self.alpha = 0.45     
        self.stride = 4       
        self.threshold = 0.55 
        self.process_every = 1 
        self.max_pose = args.max_pose_people

        # Dashboard states
        self.fight_votes = deque(maxlen=10)
        self.last_bboxes = {}
        self.last_kpts = {}
        self.last_alert = False
        self.last_probs = {} 
        self.max_conf = 0.0
        self.fps_history = deque(maxlen=60)
        self.last_time = time.time()
        self.frame_count = 0

    def _cleanup_state(self, current_ids, max_age_frames=100):
        self.frame_count += 1
        for tid in current_ids:
            self.last_seen[tid] = self.frame_count
        
        if self.frame_count % 30 == 0: # Periodic cleanup
            to_remove = [tid for tid, last_f in self.last_seen.items() if self.frame_count - last_f > max_age_frames]
            for tid in to_remove:
                self.prev_centers.pop(tid, None)
                self.smoothed_bboxes.pop(tid, None)
                self.pose_memory.pop(tid, None)
                self.last_seen.pop(tid, None)
                pids_to_remove = [pid for pid in self.pair_buffers if tid in pid]
                for pid in pids_to_remove:
                    self.pair_buffers.pop(pid, None)

    def parse_source(self, source):
        if isinstance(source, str) and source.isdigit():
            return int(source)
        return source

    def draw_skeleton(self, frame, kpts):
        edges = [(15, 13), (13, 11), (16, 14), (14, 12), (11, 12), (5, 11), (6, 12), (5, 6), (5, 7), (6, 8), (7, 9), (8, 10)]
        for e in edges:
            p1 = kpts[e[0]]; p2 = kpts[e[1]]
            if p1[2] > 0.3 and p2[2] > 0.3:
                cv2.line(frame, (int(p1[0]), int(p1[1])), (int(p2[0]), int(p2[1])), (0, 255, 255), 2)
        for p in kpts:
            if p[2] > 0.3:
                cv2.circle(frame, (int(p[0]), int(p[1])), 4, (255, 0, 255), -1)

    def step(self, frame, idx):
        h, w = frame.shape[:2]
        results = self.det_model.track(frame, persist=True, classes=[0], tracker=self.args.tracker, 
                                      conf=0.3, iou=0.5, imgsz=512, max_det=20, verbose=False)

        tids = []
        boxes = {}
        centers = {}

        if results[0].boxes.id is not None:
            ids = results[0].boxes.id.cpu().numpy().astype(int)
            bxs = results[0].boxes.xyxy.cpu().numpy()

            for tid, box in zip(ids, bxs):
                tids.append(tid)
                
                # EMA BBox Smoothing
                if tid not in self.smoothed_bboxes:
                    self.smoothed_bboxes[tid] = box
                else:
                    self.smoothed_bboxes[tid] = 0.6 * box + 0.4 * self.smoothed_bboxes[tid]
                
                boxes[tid] = self.smoothed_bboxes[tid]
                
                # EMA Center Smoothing
                c = np.array([(box[0]+box[2])/2, (box[1]+box[3])/2])
                if tid not in self.prev_centers: self.prev_centers[tid] = c
                else: 
                    self.prev_centers[tid] = 0.6 * c + 0.4 * self.prev_centers[tid]
                centers[tid] = self.prev_centers[tid]

        self._cleanup_state(tids)

        pairs = []
        interacting = set()
        diagonal = np.sqrt(w**2 + h**2)
        for i in range(len(tids)):
            for j in range(i+1, len(tids)):
                a, b = sorted([tids[i], tids[j]])
                
                dist = np.linalg.norm(centers[a] - centers[b]) / diagonal
                if dist < self.proximity:
                    pairs.append((a, b))
                    interacting.add(a)
                    interacting.add(b)

        # Always extract poses for up to max_pose people to show on dashboard,
        # prioritizing those who are close/interacting.
        marked = list(interacting)
        for tid in tids:
            if tid not in marked and len(marked) < self.max_pose:
                marked.append(tid)
        kpts_now = {}
        if marked:
            crops, meta = [], []
            for tid in marked:
                if tid not in boxes: continue
                c, _, inv = self.pose_model.preprocess(frame, boxes[tid])
                crops.append(c); meta.append((tid, inv))
            if crops:
                out = self.pose_model.infer_batch(crops)
                for k, (tid, inv) in zip(out, meta):
                    k = restore_coords(k, inv) # Keep in pixels
                    
                    prev_k = self.pose_memory.get(tid, {}).get("kpts")
                    if prev_k is not None:
                        smoothed = k.copy()
                        for j in range(17):
                            if k[j, 2] < 0.2: smoothed[j, :2] = prev_k[j, :2]
                            else: smoothed[j, :2] = 0.6 * k[j, :2] + 0.4 * prev_k[j, :2]
                        k = smoothed

                    kpts_now[tid] = k
                    self.pose_memory[tid] = {"kpts": k, "prev_kpts": prev_k, "age": 0}

        alert_raw = False
        new_probs = {}
        max_p = 0.0
        active_pairs = set()
        for a, b in pairs:
            k1 = kpts_now.get(a)
            if k1 is None: k1 = self.pose_memory.get(a, {}).get("kpts")
            k2 = kpts_now.get(b)
            if k2 is None: k2 = self.pose_memory.get(b, {}).get("kpts")
            if k1 is None or k2 is None: continue

            # Temporal motion: movement of person A and B relative to their own previous frame
            prev1 = self.pose_memory.get(a, {}).get("prev_kpts")
            prev2 = self.pose_memory.get(b, {}).get("prev_kpts")
            mot_a = np.mean(np.linalg.norm(k1[:, :2] - prev1[:, :2], axis=1)) if prev1 is not None else 0.0
            mot_b = np.mean(np.linalg.norm(k2[:, :2] - prev2[:, :2], axis=1)) if prev2 is not None else 0.0
            combined_motion = (mot_a + mot_b) / 2.0 / diagonal

            # Only process pairs with active movement
            if combined_motion < 0.002: continue

            pid = (a, b)
            active_pairs.add(pid)
            if pid not in self.pair_buffers:
                self.pair_buffers[pid] = {"A": deque(maxlen=36), "B": deque(maxlen=36), "P": deque(maxlen=8)}

            buf = self.pair_buffers[pid]
            buf["A"].append(k1); buf["B"].append(k2)

            if len(buf["A"]) == 36 and idx % self.stride == 0:
                k1_seq = np.array(buf["A"])
                k2_seq = np.array(buf["B"])

                # Sequence-wide motion heuristic: check if there is enough dynamic movement
                # across the 36-frame window to justify a TCN inference.
                v1 = np.mean(np.linalg.norm(np.diff(k1_seq[:, :, :2], axis=0), axis=-1))
                v2 = np.mean(np.linalg.norm(np.diff(k2_seq[:, :, :2], axis=0), axis=-1))
                
                if (v1 + v2) / 2.0 / diagonal > 0.003:
                    f = self.feature_extractor.extract(k1_seq, k2_seq)
                    self.interpreter.set_tensor(self.inp[0]["index"], f[np.newaxis, ...].astype(np.float32))
                    self.interpreter.invoke()
                    prob = self.interpreter.get_tensor(self.out[0]["index"])[0][0]
                    buf["P"].append(prob)

            if buf["P"]:
                avg_p = np.mean(buf["P"])
                new_probs[pid] = avg_p
                max_p = max(max_p, avg_p)
                if avg_p > self.threshold: alert_raw = True

        # Aggressive stale buffer removal
        for pid in list(self.pair_buffers.keys()):
            if pid not in active_pairs:
                del self.pair_buffers[pid]

        self.fight_votes.append(alert_raw)
        # Alert robustness: 6/10 recent detections AND a high-confidence peak (>0.7)
        alert = (sum(self.fight_votes) >= 6) and (max_p > 0.7)

        self.last_bboxes = boxes; self.last_kpts = kpts_now; self.last_alert = alert
        self.last_probs = new_probs; self.max_conf = max_p
        return alert

    def run(self, source):
        source = self.parse_source(source)
        stream = FastStreamGrabber(source)
        rec = RecordingManager(stream.native_fps, 1280, 720)

        cv2.namedWindow("Fight Detection Dashboard", cv2.WINDOW_NORMAL)
        
        last_idx = -1
        ui_last_time = 0
        canvas = np.zeros((800, 1600, 3), dtype=np.uint8); canvas[:] = COLOR_BG

        while True:
            ret, frame, frame_idx = stream.read(last_idx)
            
            if frame is None:
                if not ret and frame_idx > 0: # Stream ended
                    break
                time.sleep(0.005) # Prevent busy-wait
                continue

            frames_to_write = 1 if last_idx == -1 else frame_idx - last_idx
            last_idx = frame_idx

            # Proper Loop FPS
            curr_time = time.time()
            dt = curr_time - self.last_time
            self.last_time = curr_time
            if dt > 0: self.fps_history.append(1.0 / dt)
            avg_fps = sum(self.fps_history) / len(self.fps_history) if self.fps_history else 0
            
            # FIX: No frame skipping allowed for 12 FPS streams
            alert = self.step(frame, frame_idx)

            # --- RENDER PREVIEW (Fast, every frame for recording) ---
            preview = frame.copy()
            for tid, box in self.last_bboxes.items():
                x1, y1, x2, y2 = box.astype(int)
                color = COLOR_TRACK if not alert else COLOR_ALERT
                cv2.rectangle(preview, (x1, y1), (x2, y2), color, 2)
                cv2.rectangle(preview, (x1, y1-25), (x1+60, y1), color, -1)
                cv2.putText(preview, f"ID {tid}", (x1+5, y1-7), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (255,255,255), 1)

            for tid, kpts in self.last_kpts.items():
                self.draw_skeleton(preview, kpts)

            if alert:
                cv2.rectangle(preview, (0, 0), (1280, 45), COLOR_ALERT, -1)
                cv2.putText(preview, f"!!! VIOLENCE DETECTED ({self.max_conf*100:.1f}%) !!!", 
                            (15, 33), cv2.FONT_HERSHEY_DUPLEX, 0.9, (255, 255, 255), 2)

            rec.update(preview, alert, count=frames_to_write)

            # --- RENDER DASHBOARD (Heavy, lower frequency) ---
            if curr_time - ui_last_time > 1/15.0:
                ui_last_time = curr_time
                canvas[40:760, 40:1320] = preview

                # Insights Panel
                panel_x = 1340
                cv2.rectangle(canvas, (panel_x, 40), (1560, 760), COLOR_PANEL, -1)
                cv2.putText(canvas, "ACTIVITY MONITOR", (panel_x+10, 75), cv2.FONT_HERSHEY_DUPLEX, 0.6, COLOR_ACCENT, 1)

                # Dynamic Status Logic
                num_persons = len(self.last_bboxes)
                num_pairs = len(self.last_probs)
                
                if alert:
                    status_str, status_col = "!!! VIOLENCE !!!", COLOR_ALERT
                elif num_pairs > 0:
                    status_str, status_col = "ANALYZING PAIRS", COLOR_INFO
                elif num_persons > 0:
                    status_str, status_col = "MONITORING", COLOR_ACCENT
                else:
                    status_str, status_col = "IDLE (NO PEOPLE)", (120, 120, 120)

                y_off = 130
                stats = [
                    ("System State", status_str, status_col),
                    ("Active Persons", f"{num_persons}", COLOR_TEXT),
                    ("Interactions", f"{num_pairs} active", COLOR_INFO if num_pairs > 0 else COLOR_TEXT),
                    ("Inference Speed", f"{avg_fps:.1f} FPS", COLOR_INFO),
                    ("Peak Confidence", f"{self.max_conf*100:.1f}%", COLOR_ALERT if self.max_conf > self.threshold else COLOR_TEXT),
                ]

                for label, val, col in stats:
                    cv2.putText(canvas, label, (panel_x+15, y_off), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (180, 180, 180), 1)
                    cv2.putText(canvas, val, (panel_x+15, y_off+25), cv2.FONT_HERSHEY_SIMPLEX, 0.7, col, 2)
                    y_off += 70

                # Pair Analysis
                if num_pairs > 0:
                    cv2.putText(canvas, "INTERACTION PROBS", (panel_x+10, y_off+20), cv2.FONT_HERSHEY_DUPLEX, 0.5, COLOR_ACCENT, 1)
                    y_off += 50
                    for pair, prob in sorted(self.last_probs.items(), key=lambda x: x[1], reverse=True)[:5]:
                        p_col = COLOR_ALERT if prob > self.threshold else COLOR_ACCENT
                        cv2.putText(canvas, f"IDs {pair[0]}+{pair[1]}", (panel_x+15, y_off), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (180, 180, 180), 1)
                        cv2.rectangle(canvas, (panel_x+15, y_off+10), (panel_x+175, y_off+22), (50, 50, 50), -1)
                        cv2.rectangle(canvas, (panel_x+15, y_off+10), (panel_x+15+int(160*prob), y_off+22), p_col, -1)
                        cv2.putText(canvas, f"{prob:.2f}", (panel_x+180, y_off+21), cv2.FONT_HERSHEY_SIMPLEX, 0.45, p_col, 1)
                        y_off += 45

                if rec.active:
                    cv2.circle(canvas, (panel_x+30, 730), 8, COLOR_ALERT, -1)
                    cv2.putText(canvas, "REC ACTIVE", (panel_x+50, 737), cv2.FONT_HERSHEY_SIMPLEX, 0.6, COLOR_ALERT, 2)

                # Top Dashboard Header
                header_col = COLOR_ALERT if alert else COLOR_PANEL
                cv2.rectangle(canvas, (40, 0), (1320, 35), header_col, -1)
                status_text = f"SYSTEM ALERT: VIOLENCE DETECTED" if alert else "SECURITY FEED STABLE"
                cv2.putText(canvas, status_text, (50, 25), cv2.FONT_HERSHEY_DUPLEX, 0.7, (255, 255, 255), 1)

            cv2.imshow("Fight Detection Dashboard", canvas)
            if cv2.waitKey(1) & 0xFF == ord('q'): break

        stream.stop(); rec.stop(); cv2.destroyAllWindows()

if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--source", required=True)
    p.add_argument("--det_model", default="models/yolov8s.pt")
    p.add_argument("--pose_model", default="models/rtmpose-s-c54166.onnx")
    p.add_argument("--tcn_model", default="models/tcn_model.tflite")
    p.add_argument("--tracker", default="bytetrack_stable.yaml")
    p.add_argument("--device", default="cpu")
    p.add_argument("--proximity", type=float, default=0.25)
    p.add_argument("--process_every", type=int, default=1) # Set to 1 for smoothness
    p.add_argument("--max_pose_people", type=int, default=2)
    p.add_argument("--pose_threads", type=int, default=4)
    args = p.parse_args()
    InferencePipeline(args).run(args.source)
